trigger:
- main
pool: 
  vmImage: ubuntu-latest

variables:
  buildConfig: 'Release'

steps:
- script: dotnet build --configuration $(buildConfig)
  displayName: 'dotnet build $(buildConfig)'